defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password:
  min_messages: warning

development:
  <<: *defaults
  database: carbometer_development

test:
  <<: *defaults
  database: carbometer_test
