development:
  adapter: postgresql
  encoding: unicode
  database: carbometer_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: carbometer_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: carbometer
  pool: 5
  username: postgres
  password:
