require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AuthenticationsController do

  # This should return the minimal set of attributes required to create a valid
  # Authentication. As you add validations to Authentication, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "renders a page" do
      get :index
      response.should be_success
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested authentication" do
      pending
      authentication = Authentication.create! valid_attributes
      expect {
        delete :destroy, :id => authentication.id
      }.to change(Authentication, :count).by(-1)
    end

    it "redirects to the authentications list" do
      pending
      authentication = Authentication.create! valid_attributes
      delete :destroy, :id => authentication.id
      response.should redirect_to(authentications_url)
    end
  end

end
